//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtcSimController.SiteReflection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtcSimController.SiteReflection.Resources.FormElements", typeof(FormElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdoICAorIATA.
        /// </summary>
        internal static string AIRLINE_FORMAT_ID {
            get {
                return ResourceManager.GetString("AIRLINE_FORMAT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selAirport.
        /// </summary>
        internal static string AIRPORT_SELECTION_ID {
            get {
                return ResourceManager.GetString("AIRPORT_SELECTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtClearance.
        /// </summary>
        internal static string CLEARANCE_TEXTBOX_ID {
            get {
                return ResourceManager.GetString("CLEARANCE_TEXTBOX_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayMode.
        /// </summary>
        internal static string DIFFICULTY_ID {
            get {
                return ResourceManager.GetString("DIFFICULTY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frmOptions.
        /// </summary>
        internal static string OPTIONS_FORM_ID {
            get {
                return ResourceManager.GetString("OPTIONS_FORM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleMarks.
        /// </summary>
        internal static string SCALE_MARKERS_ID {
            get {
                return ResourceManager.GetString("SCALE_MARKERS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindChance.
        /// </summary>
        internal static string WIND_CHANCE_ID {
            get {
                return ResourceManager.GetString("WIND_CHANCE_ID", resourceCulture);
            }
        }
    }
}
