//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtcSimController.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtcSimController.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details: {0}.
        /// </summary>
        internal static string ADDITIONAL_INFO {
            get {
                return ResourceManager.GetString("ADDITIONAL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The simulation data broker object was not provided to the controller..
        /// </summary>
        internal static string BROKER_CONNECTION_FAIL {
            get {
                return ResourceManager.GetString("BROKER_CONNECTION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Active.
        /// </summary>
        internal static string CONTROLLER_READY {
            get {
                return ResourceManager.GetString("CONTROLLER_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATC-SIM AI By Cory Gehr (2015, 2018).
        /// </summary>
        internal static string CREDIT {
            get {
                return ResourceManager.GetString("CREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading radar scope.
        /// </summary>
        internal static string ENVIRONMENT_LOAD {
            get {
                return ResourceManager.GetString("ENVIRONMENT_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required form elements could not be found. Application will now exit..
        /// </summary>
        internal static string ENVIRONMENT_LOAD_FAIL {
            get {
                return ResourceManager.GetString("ENVIRONMENT_LOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading environment details.
        /// </summary>
        internal static string ENVIRONMENT_SETUP {
            get {
                return ResourceManager.GetString("ENVIRONMENT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        internal static string ERROR_BASE {
            get {
                return ResourceManager.GetString("ERROR_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general exception has occurred. Application will now exit..
        /// </summary>
        internal static string ERROR_GENERIC {
            get {
                return ResourceManager.GetString("ERROR_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EXPLICIT] {0}.
        /// </summary>
        internal static string EXPLICIT_BASE {
            get {
                return ResourceManager.GetString("EXPLICIT_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] {0}.
        /// </summary>
        internal static string INFO_BASE {
            get {
                return ResourceManager.GetString("INFO_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from Selenium Server..
        /// </summary>
        internal static string SELENIUM_DISCONNECTED {
            get {
                return ResourceManager.GetString("SELENIUM_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Selenium Server.
        /// </summary>
        internal static string SELENIUM_SETUP {
            get {
                return ResourceManager.GetString("SELENIUM_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting settings form.
        /// </summary>
        internal static string SETTINGS_SUBMITTED {
            get {
                return ResourceManager.GetString("SETTINGS_SUBMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WARNING] {0}.
        /// </summary>
        internal static string WARNING_BASE {
            get {
                return ResourceManager.GetString("WARNING_BASE", resourceCulture);
            }
        }
    }
}
